### ISSUE TITLE
Bad double quote substitution

### ISSUE THREAD

**Issue by miceno** [dakanji/G2Project-modules#13]
Automatic code styling is wrongly changing double quotes for quotes in the following code:

https://github.com/dakanji/G2Project-modules/blob/7498abb331eb2b7f9f134352ddf1d6863eeb4e0d/modules/integrity/classes/IntegrityCheckTask.class#L178-L191

It also happens in this:
https://github.com/dakanji/G2Project-modules/blob/7498abb331eb2b7f9f134352ddf1d6863eeb4e0d/modules/integrity/classes/IntegrityCheckTask.class#L280-L293

**Comment by dakanji** [comment]
That looks like it was a manual change actually and not by the cs fixer.
